version: '3'

x-airflow-common:
  &airflow-common
  image: apache/airflow:2.7.1
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__FERNET_KEY=your_fernet_key
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    
  volumes:
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - D:/lg/dags:/opt/airflow/dags
    - D:/lg/etl:/opt/airflow/etl
    - D:/lg/data:/opt/airflow/data
    - D:/lg/requirements.txt:/requirements.txt
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"   # если 5432 занят, можно вынести наружу на 5433
    volumes:
      - postgres_airflow:/var/lib/postgresql/data
      

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

volumes:
  postgres_airflow:
